[project]
name = "fastar"
version = "0.1.0"
description = "Stellar population synthesis tools"
authors = [
  { name = "Ignacio Martin Navarro", email = "ignacio.martin@iac.es" }
]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.8"

# Dependencies your code needs to run
dependencies = [
  "numpy",
  "matplotlib",
  "jax",
  "flax",
  "h5py",
  "astropy",
  "astroquery",
  "h5py",
  "tqdm",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["fastar"]  