[project]
dynamic = ["version"]
name = "fastar"
description = "Stellar population synthesis tools"
authors = [
  { name = "Ignacio Martin Navarro", email = "ignacio.martin@iac.es" }
]
urls = { "homepage" = "https://github.com/inavarro/fastar" }
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.8"
dependencies = [
  "astropy",
  "astroquery",
  "flax",
  "h5py",
  "jax",
  "matplotlib",
  "numpy",
  "tqdm",
]

[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["fastar"]

[tool.setuptools_scm]
version_file = "fastar/_version.py"

[tool.ruff]
line-length = 79

[tool.ruff.format]
quote-style = "single"
