[project]
dynamic = ["version"]
name = "fastar"
description = "Stellar population synthesis tools"
authors = [
  { name = "Ignacio Martin Navarro", email = "ignacio.martin@iac.es" }
]
urls = { "homepage" = "https://github.com/inavarro/fastar" }
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.10.12"
dependencies = [
  "astropy>=6.1.7",
  "astroquery>=0.4.8",
  "flax>=0.10.5",
  "h5py>=3.12.1",
  "jax>=0.6.0",
  "matplotlib>=3.10.1",
  "numpy>=2.2.5",
  "tqdm>=4.67.1",
]

[project.optional-dependencies]
dev = [
  "build>=1.2.2.post1",
  "flake8>=4.0.1",
  "flake8-quotes>=3.4.0",
  "pylint>=2.12.2",
  "pytest>=8.3.4",
  "ruff>=0.12.3",
]
docs = [
  "Sphinx>=4.3.2",
  "sphinx-rtd-theme>=1.3.0"
]

[build-system]
requires = ["setuptools>=65.5.1", "wheel>=0.41.1", "setuptools_scm>=8.3.1"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["fastar"]

[tool.setuptools_scm]
version_file = "fastar/_version.py"

[tool.ruff]
line-length = 79

[tool.ruff.format]
quote-style = "single"
