name: Docs
on:
  push:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ ! contains(github.event.head_commit.message, '[no docs]') }}

    steps:
    - uses: actions/checkout@v5
    - name: Setup the environment
      uses: ./.github/actions/setup
    - name: Build documentation
      run: make docs-html
    # - name: Upload static files as artifact
    #   uses: actions/upload-pages-artifact@v4
    #   with:
    #     path: _build/

  # deploy:
  #   needs: build

  #   permissions:
  #     pages: write
  #     id-token: write

  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}

  #   runs-on: ubuntu-22.04
  #   steps:
  #     - name: Deploy to GitHub Pages
  #       uses: actions/deploy-pages@v4
