name: Tests

on:
  push:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  lint-format:
    runs-on: ubuntu-22.04
    steps:
      - run: sudo apt -y update
      - uses: actions/checkout@v4
      - name: Setup the environment
        uses: ./.github/actions/setup
      - run: make lint
      - run: make format
  test:
    runs-on: ubuntu-22.04
    if: ${{ ! contains(github.event.head_commit.message, '[no test]') }}
    strategy:
      matrix:
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'

    steps:
    - run: sudo apt -y update
    - uses: actions/checkout@v5

    - name: Set up the environment
      uses: ./.github/actions/setup
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run tests
      run: |
        make tests
